---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-hoprd-{{ nodes }}-{{ workloadName }}
  namespace: k6-operator-system
spec:
  parallelism: 1
  script:
    localFile: /app/hoprnet/send-messages.test.js
  separate: true
  arguments: --tag testid={{ testid }} --summary-export=/test-results/k6/test-execution-$(date +%Y%m%d-%H%M%S).json
  runner:
    image: europe-west3-docker.pkg.dev/hoprassociation/docker-images/hoprd-k6:latest
    securityContext:
      runAsUser: 0
    resources:
      limits:
        cpu: 3
        memory: 3Gi
      requests:
        cpu: 3
        memory: 3Gi
    env:
      - name: TOPOLOGY_NAME
        value: {{ topologyName }}
      - name: WORKLOAD_NAME
        value: {{ workloadName }}
      - name: REQUESTS_PER_SECOND_PER_VU
        value: "{{ requestsPerSecondPerVu }}"
      - name: DURATION
        value: "{{ duration }}"
      - name: VU_PER_ROUTE
        value: "{{ vuPerRoute }}"
      - name: HOPRD_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: hoprd-api-tokens
            key: {{ topologyName }}
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: http://kube-prometheus-stack-prometheus.monitoring.svc:9090/api/v1/write
      - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
        value: 'true'
      - name: K6_OUT
        value: xk6-prometheus-rw
    volumes:
      - name: test-results
        persistentVolumeClaim:
          claimName: test-results
    volumeMounts:
      - name: test-results
        mountPath: /test-results/k6
